# Generated by Django 5.0.4 on 2024-05-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshop", "0002_master_price_alter_service_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="master",
            name="photo",
            field=models.ImageField(default="images/default.jpg", upload_to="images/"),
        ),
    ]
