# Generated by Django 5.0.4 on 2024-05-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshop", "0004_alter_master_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="client_id",
        ),
        migrations.RemoveField(
            model_name="order",
            name="total_price",
        ),
        migrations.AddField(
            model_name="order",
            name="hours_worked",
            field=models.IntegerField(default=0),
        ),
    ]
